# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='modified_on',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
