# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20151214_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='start_date',
            new_name='start',
        ),
    ]
