# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0008_auto_20151214_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'permissions': (('unlock_worksheet', 'Can update worksheet'),)},
        ),
    ]
