# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_auto_20151214_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='irc_robustness',
            field=models.IntegerField(default=0, null=True, verbose_name='IRC robustness'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='pre_crisis_population',
            field=models.IntegerField(default=0, null=True, verbose_name='IRC robustness'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='pre_crisis_vulnerability_rank',
            field=models.IntegerField(default=0, null=True, verbose_name='Pre-crisis vulnerability rank.'),
        ),
    ]
