# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_auto_20151214_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='number_affected',
            field=models.IntegerField(default=0, help_text='See notes on next page re: affected', verbose_name='Affected'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='number_deaths',
            field=models.IntegerField(default=0, help_text='How many deaths have been reported (in this country due to this emergency)?', verbose_name='Number of deaths'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='number_displaced',
            field=models.IntegerField(default=0, verbose_name='Displaced'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='number_injuries',
            field=models.IntegerField(default=0, help_text='How many injuries have been reported (in this country due to this emergency)?', verbose_name='Number of injuries'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='pre_crisis_population',
            field=models.IntegerField(default=0, null=True, verbose_name='Pre-crisis population'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='pre_crisis_vulnerability_rank',
            field=models.IntegerField(default=0, null=True, verbose_name='Pre-crisis vulnerability rank'),
        ),
    ]
