# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0011_auto_20151214_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='emergency_classification_rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Emergency classification rank'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='irc_robustness',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IRC robustness'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='pre_crisis_population',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pre-crisis population'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='pre_crisis_vulnerability_rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pre-crisis vulnerability rank'),
        ),
    ]
