# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_auto_20151216_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_decision',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'The IRC country program will decide if they will respond'), (3, 'IRC will respond'), (1, 'IRC will not respond')], default=1, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_management',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Country program leads'), (2, 'EPRU leads')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_stance',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Lower Level/One/A'), (2, 'Mid Level/Two/B'), (3, 'High Level/Three/C')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'One team'), (2, 'Two teams')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Date Classified'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='modified_on',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='number_affected',
            field=models.IntegerField(default=0, verbose_name='Affected'),
        ),
    ]
