# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_auto_20151216_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='irc_country_program',
            field=models.BooleanField(default=False, verbose_name='The IRC already has a country program in this country.'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_decision',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (2, 'The IRC country program will decide if they will respond'), (3, 'IRC will respond'), (1, 'IRC will not respond')], default=1, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_management',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Country program leads'), (2, 'EPRU leads')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_stance',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'A'), (2, 'B'), (3, 'C')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recorded_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'One team'), (2, 'Two teams')], default=0, null=True, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='taken_decision',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (2, 'The IRC country program will decide if they will respond'), (3, 'IRC will respond'), (1, 'IRC will not respond')], default=0, null=True, verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='taken_management',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Country program leads'), (2, 'EPRU leads')], default=0, null=True, verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='taken_stance',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'A'), (2, 'B'), (3, 'C')], default=0, null=True, verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='taken_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'One team'), (2, 'Two teams')], default=0, null=True, verbose_name='Taken'),
        ),
    ]
