# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0017_auto_20160105_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='is_official',
            field=models.BooleanField(default=True, verbose_name='Has this worksheet done by a classifier?'),
        ),
    ]
